### ISSUE TITLE
documentation refactoring

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/e3s#29]
let's simplify a bit installatoin and configuration steps:
1. [Installation](https://github.com/zebrunner/e3s/blob/main/docs/installation.md) should be renamed to `ECS E3S cluster creation`
2. Move [Cleanup](https://github.com/zebrunner/e3s/blob/main/docs/cleanup.md) and make it as part of `ECS E3S cluster creation`
3. [Configuration](https://github.com/zebrunner/e3s/blob/main/docs/configuration.md) should be renamed to `Usage`
4. Usage should include git clone steps for this particular repo, cd to e3s, update env files
5. Think about adding optional steps for `data.env` file modification with a notes about 3rd party DB and redis
6. Make [Capabilities](https://github.com/zebrunner/e3s/blob/main/docs/capabilities.md) and [Errors](https://github.com/zebrunner/e3s/blob/main/docs/errors.md) as part of Usage

**Comment by dmtgrinevich** [comment]
Done
