### ISSUE TITLE
ALB steps generation updates

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/e3s#30]
1. fix misprint in command
```
aws elbv2 describe-load-balancer --name e3s-{Env}-alb
```
change to 
```
aws elbv2 describe-load-balancers --name e3s-{Env}-alb
```

2. add arn to the end of the commands, i.e.:
```
aws elbv2 modify-target-group-attributes --attributes Key=deregistration_delay.timeout_seconds,Value=660 --target-group-arn <e3s-tg-arn>
aws elbv2 describe-target-group-attributes --target-group-arn <e3s-tg-arn>
```

3. For `Create listener. Update LoadBalancerArn and TargetGroupArn in e3s-listener.json file, specify certificate to use` step inside e3s-listener.json add templated vars to replace aka `e3s-alb-arn` and `e3s-tg-arn`

4. add arn to the end of the commands, i.e.:
```
aws elbv2 describe-listeners --load-balancer-arn <e3s-alb-arn>
```

**Comment by dmtgrinevich** [comment]
Done
