### ISSUE TITLE
all aws cli commands should be writted using code snippet

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/e3s#40]
we have to use `single line` or
```
multiply
lines
```
snippets for all aws cli commands. 

it should be displayed in diferent format and provide copy functionality by default for full command

**Comment by dmtgrinevich** [comment]
Refs inside of code snippet are shown as plain text, example:
`[file://e3s-linux-asg.json/](cli-input/cluster/e3s-linux-asg.json)`
expected
[file://e3s-linux-asg.json/](cli-input/cluster/e3s-linux-asg.json)

**Comment by dmtgrinevich** [comment]
Tested by completing all deploy steps by creating new cluster
