### ISSUE TITLE
let's keep only recommended instance type c5a.4xlarge

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/e3s#41]
we have to specify recommended and not minimal by default:
Create auto scaling group. Additionly in [file://e3s-asg.json](https://github.com/zebrunner/e3s/blob/main/docs/cli-input/cluster/e3s-linux-asg.json) file should be specified Availability Zones, Subnets and compute optimized instance types (Recommended min instance type is c5a.2xlarge)

To use wights, 2nd option should be c5a.8xlarge

**Comment by vdelendik** [comment]
same for windows:
Create auto scaling group. Additionly in [file://e3s-windows-asg.json](https://github.com/zebrunner/e3s/blob/main/docs/cli-input/cluster/e3s-windows-asg.json) file should be specified Availability Zones, Subnets and compute optimized instance types (Recommended min instance type is c5a.2xlarge)

**Comment by dmtgrinevich** [comment]
Done
