### ISSUE TITLE
as a note add information about updating `{VpcCidrBlock}` in advance

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/e3s#42]
Encode [user data](https://github.com/zebrunner/e3s/blob/main/docs/cli-input/cluster/e3s-windows-userdata.txt) to base64. Make sure that {VpcCidrBlock} is specified for -AwsvpcAdditionalLocalRoutes flag in windows userdata

**Comment by dmtgrinevich** [comment]
Should be added new action to deploy policy

**Comment by akamarouski** [comment]
> Should be added new action to deploy policy

Done

**Comment by dmtgrinevich** [comment]
Tested by completing all deploy steps by creating new cluster
