### ISSUE TITLE
remove `[Optional] Add crons for min/max capacity upgrade` step from `ecs_e3s_cluster_creation.md`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/e3s#43]
that's an edvanced usage, let's hide so far by complete romoval from doc

**Comment by vdelendik** [comment]
instead I'd recommend to add steps about enabling forecast for autoscaling

**Comment by dmtgrinevich** [comment]
Done, will be tested on new cluster creation from e3s repo
