### ISSUE TITLE
introduce e3s developer role

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/e3s#7]
we need a role for a developer or deployer with a little bit wider range of permissions. So we could review and collect more information about ecs, asg etc.

**Comment by dmtgrinevich** [comment]
Done, should be tested by deploying e3s from scratch with all 3 policies

**Comment by dmtgrinevich** [comment]
Tested by completing all steps from installation and cleanup docs by user profile with monitor, manage and deploy policies
