### ISSUE TITLE
add valid s3 preparation steps

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/e3s#8]
we have hardcoded `zebrunner.com-engine` s3 bucket in the installation artifacts.
1. Let's add into the installation separate step to create new s3 bucket
2. Add step about renaming (so far it exists in 2 files only)

all s3 buckets in AWS should be unique that's why it is impossible to generate the same on the customer side

**Comment by dmtgrinevich** [comment]
Done, should be tested by deploying e3s from scratch

**Comment by dhreben** [comment]
Verified.
